# Generated by Django 3.0.6 on 2020-05-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=32)),
                ('mobile', models.IntegerField(max_length=10)),
                ('address', models.TextField()),
                ('taluka', models.TextField()),
                ('post', models.TextField()),
                ('district', models.TextField()),
            ],
        ),
    ]
