# Generated by Django 3.0.6 on 2020-05-29 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_auto_20200529_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='mobile',
            new_name='mobile_number',
        ),
    ]
