# Generated by Django 3.0.6 on 2020-05-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_auto_20200529_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile_number',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
    ]
