# Generated by Django 3.0.6 on 2020-05-27 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0005_auto_20200519_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='middle_name',
        ),
    ]
