# Generated by Django 3.0.6 on 2020-05-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0006_auto_20200527_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='password',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
