# Generated by Django 3.0.6 on 2020-06-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0007_supplier_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='email_optional',
            field=models.EmailField(blank=True, default='-', max_length=255),
        ),
    ]
