# Generated by Django 3.0.6 on 2020-06-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0008_auto_20200602_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_type',
            field=models.CharField(choices=[('Manufacturer', 'Manufacturer'), ('Exporter', 'Exporter'), ('Wholesale Distributor', 'Wholesale Distributor'), ('Wholesale Seller', 'Wholesale Seller'), ('Wholesale Supplier', 'Wholesale Supplier'), ('Wholesale Trader', 'Wholesale Trader'), ('Authorized Distributor', 'Authorized Distributor'), ('Channel Partner', 'Channel Partner'), ('Retailer', 'Retailer')], max_length=255),
        ),
    ]
