# Generated by Django 3.0.6 on 2020-06-11 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0010_auto_20200610_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='Pics')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='additional_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='arrival',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(default='-', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='main_category',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='requested_quote',
            field=models.DecimalField(decimal_places=0, default='-', max_digits=256),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_main_category',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('meter', 'meter'), ('kg', 'kg'), ('pack', 'pack'), ('unit', 'unit')], default='-', max_length=255),
        ),
        migrations.CreateModel(
            name='Sub_Main_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='Pics')),
                ('main_categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supplier.Main_Categories')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sub_main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supplier.Sub_Main_Category')),
            ],
        ),
    ]
