# Generated by Django 3.0.6 on 2020-06-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0011_auto_20200611_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='requested_quote',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=256),
        ),
    ]
