# Generated by Django 3.0.6 on 2020-06-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0012_auto_20200611_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('meter', 'meter'), ('Kg', 'Kg'), ('pack', 'pack'), ('unit', 'unit')], default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_date',
            field=models.DateField(verbose_name='DD/MM/YYYY'),
        ),
    ]
