# Generated by Django 3.0.6 on 2020-06-15 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0014_auto_20200615_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_main_category',
            name='main_categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Sub_Main_Category',
        ),
    ]
