# Generated by Django 3.0.6 on 2020-06-15 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0015_auto_20200615_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_Main_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='Pics')),
                ('main_categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supplier.Main_Categories')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sub_main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supplier.Sub_Main_Category')),
            ],
        ),
    ]
