# Generated by Django 3.0.6 on 2020-06-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0016_category_sub_main_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(default='', upload_to='ProductImage'),
        ),
    ]
