# Generated by Django 3.0.6 on 2020-06-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0018_remove_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('meter', 'meter'), ('Kg', 'Kg'), ('pack', 'pack'), ('unit', 'unit')], default='-', max_length=255),
        ),
    ]
