# Generated by Django 3.0.6 on 2020-06-22 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0019_product_unit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
