# Generated by Django 3.0.6 on 2020-06-22 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0023_auto_20200622_1317'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
