# Generated by Django 3.0.6 on 2020-06-22 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0024_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(default='', upload_to='ProductImage')),
                ('name', models.CharField(max_length=255)),
                ('arrival', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=255)),
                ('unit', models.CharField(choices=[('meter', 'meter'), ('Kg', 'Kg'), ('pack', 'pack'), ('unit', 'unit')], default='-', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('main_category', models.CharField(default='-', max_length=255)),
                ('sub_main_category', models.CharField(default='-', max_length=255)),
                ('category', models.CharField(default='-', max_length=255)),
                ('brand', models.CharField(default='-', max_length=255)),
                ('code', models.CharField(default='-', max_length=255, null=True)),
                ('additional_information', models.TextField(blank=True, null=True)),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='DD/MM/YYYY')),
                ('updated_date', models.DateField(verbose_name='DD/MM/YYYY')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('clicks', models.DecimalField(decimal_places=0, max_digits=12)),
                ('requested_quote', models.DecimalField(decimal_places=0, default=0, max_digits=64)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supplier.Business')),
            ],
        ),
    ]
