# Generated by Django 3.0.6 on 2020-08-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0028_auto_20200806_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_categories',
            name='image',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
