# Generated by Django 3.0.6 on 2020-08-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0030_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
