# Generated by Django 3.0.6 on 2020-08-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0031_auto_20200822_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='requested_quote',
        ),
        migrations.AddField(
            model_name='business',
            name='profile_views',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=5, null=True),
        ),
    ]
