# Generated by Django 3.0.6 on 2020-08-26 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0033_auto_20200826_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description_eight',
            new_name='description_1',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description_five',
            new_name='description_10',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description_four',
            new_name='description_2',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description_nine',
            new_name='description_3',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description_one',
            new_name='description_4',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description_seven',
            new_name='description_5',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description_six',
            new_name='description_6',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description_ten',
            new_name='description_7',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description_three',
            new_name='description_8',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description_two',
            new_name='description_9',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='specification_eight',
            new_name='specification_1',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='specification_five',
            new_name='specification_10',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='specification_four',
            new_name='specification_2',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='specification_nine',
            new_name='specification_3',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='specification_one',
            new_name='specification_4',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='specification_seven',
            new_name='specification_5',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='specification_six',
            new_name='specification_6',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='specification_ten',
            new_name='specification_7',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='specification_three',
            new_name='specification_8',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='specification_two',
            new_name='specification_9',
        ),
    ]
